### ISSUE TITLE
Example fails when using @moduledoc false

### ISSUE THREAD

**Issue by guisehn** [surface-ui/surface_catalogue#27]
When having an example file that uses `@moduledoc false`, e.g.:

```elixir
defmodule MyProject.Components.Foo.Example do
  @moduledoc false

  use Surface.Catalogue.Example,
    subject: MyProject.Components.Foo

  def render(assigns) do
    ~F"hello world"
  end
end
```

The Surface Catalogue stops working for all components and shows the following error on the console:

```
[error] GenServer #PID<0.7860.0> terminating
** (BadMapError) expected a map, got: :hidden
    (elixir 1.12.3) lib/map.ex:464: Map.get(:hidden, "en", nil)
    (surface 0.6.1) lib/surface/catalogue.ex:72: Surface.Catalogue.get_metadata/1
    (surface_catalogue 0.2.0) lib/surface/catalogue/util.ex:82: Surface.Catalogue.Util.components_reducer/3
```

**Comment by herminiotorres** [comment]
Hi, @guisehn I think this is already fixed, and here is the PR related to this issue https://github.com/surface-ui/surface/pull/565 you can bump your surface version up to 0.7.1 according to the surface changelog https://github.com/surface-ui/surface/blob/main/CHANGELOG.md#v071-2022-02-17
