### ISSUE TITLE
Add "Slots" tab to the playground

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface_catalogue#40]
Allow setting text values to components' slots, similar to the way to we do with props.

1. Add a "Slots" tab right after the existing "Properties" tab.
2. Show a textinput (or textarea) for each available slot
3. Allow the user to define the content of the slot as the given text.

**Comment by dmnelson** [comment]
I've been meaning to get involved with this project and this seems like a good one to start. 

Just have one question though. @msaraiva do you mean this to be text only or should it allow for users to input markup as well?

**Comment by msaraiva** [comment]
Hi @dmnelson!

> I've been meaning to get involved with this project and this seems like a good one to start.

That's great! Contributions are always welcome. This feature requires a change in Surface first, so I'll work on that and ping you when it's available.

> do you mean this to be text only or should it allow for users to input markup as well?

Text only, for now.
