### ISSUE TITLE
Dependency on Mix.env() at runtime

### ISSUE THREAD

**Issue by sysashi** [surface-ui/surface_catalogue#45]
## Describe the bug

`application.ex` depends on `Mix.env` and another mix call at runtime

## How to reproduce it

1. Run a release that depends on surface_catalogue

## The behavior you expected

Builds/runs fine, without problems

## Your Environment

Surface: v0.8.1
SurfaceCatalogue: v0.5.0
LiveView: v0.17.11
Elixir: v1.14.0

**Comment by talk2MeGooseman** [comment]
Came across the same issue and had to comment out the import in the router file to get things to build and deploy.
