### ISSUE TITLE
Project deployment in prod environment fails with provided installation instructions

### ISSUE THREAD

**Issue by dushyantss** [surface-ui/surface_catalogue#7]
I'd like to start with thanking you for this amazing library.

We get the following error when we try to deploy to prod, after following all the installation steps.
```shell
** (CompileError) lib/<project-name>/router.ex:6: module Surface.Catalogue.Router is not loaded and could not be found
```

Since we are loading the project only for dev and test env in the mix.exs file, this error is expected. But, since the project also depends on `phoenix_live_reload`, if we update the mix.exs file to remove the constraint of only dev and test environments from surface_catalogue, we get the following expected error.
```shell
Dependencies have diverged:
* phoenix_live_reload (Hex package)
  the :only option for dependency phoenix_live_reload

  > In mix.exs:
    {:phoenix_live_reload, "~> 1.2", [env: :prod, repo: "hexpm", hex: "phoenix_live_reload", only: [:dev, :test]]}

  does not match the :only option calculated for

  > In deps/surface_catalogue/mix.exs:
    {:phoenix_live_reload, "~> 1.2", [env: :prod, hex: "phoenix_live_reload", repo: "hexpm", optional: false]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

Thus, the only way for us to work is to enable both surface_catalogue and phoenix_live_reload in prod, which is not optimal.

I have tried to conditionally import the module but that is not working and we get the same error about `module Surface.Catalogue.Router` not being loaded(I think that's because elixir is a compiled language and thus all the modules that are used, even if conditionally need to be loaded).

I then looked at the code of `phoenix_live_reload` to see how they conditionally load only when `code_reloading` variable is true and it makes sense and we could look into it.

Am I am being totally ignorant and there's a simple and elegant way to handle this, which I missed? 😅(I am very inexperienced in elixir)
If I have not missed anything, is there a simpler fix than implementing the `phoenix_live_reload` way?
If not, could you look into it and provide updated set of instructions for installation, which work in prod?

Any help is appreciated.

**Comment by Malian** [comment]
@dushyantss thank you for reporting this issue.

@msaraiva It seems that phoenix live dashboard as solve this by creating a `dev.ex` file that is run only when you develop on LiveDashboard:  https://github.com/phoenixframework/phoenix_live_dashboard/blob/master/dev.exs

As I am writing this, I realise that this is also the case for Surface Catalogue. I suppose we have to extract the `Surface.Catalogue.Server` in the `dev.exs` file to be able to mark the `phoenix_live_reload` `only: [:dev]`. In that case, we will have to update the [running-the-built-in-catalogue-server](https://github.com/surface-ui/surface_catalogue#running-the-built-in-catalogue-server) of the readme.

**Comment by Malian** [comment]
I proposed a fix in #8, I am waiting for feedback.

**Comment by msaraiva** [comment]
Hi @dushyantss!

Since the catalogue was initially meant to be used only in development, I need to make a couple of adjustments to make sure it's safe to use it in production.

I have a couple of questions:

1. Is your intention to make the catalogue available to untrusted users or are you going to have any kind of security layer?
2. Do you want to make playgrounds available too or just docs and examples?

**Comment by Malian** [comment]
@msaraiva maybe I misunderstood @dushyantss's issue but my understanding is that even if you set the `SurfaceCatalogue` to be only available in development, you cannot create a production release which makes it impossible to use SurfaceCatalogue today in a project.

Here are the steps to reproduce the bug:

1.  mix phx.new my_catalogue_project
2. Follow surface catalogue installation instruction
3. SECRET_KEY_BASE=$(mix phx.gen.secret) DATABASE_URL="" MIX_ENV=prod mix release

It will result in the following error:
```
** (CompileError) lib/my_catalogue_web/router.ex:5: module Surface.Catalogue.Router is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
```

I find it strange to have to remove the `Router` from the code to create a production release ;)

**Comment by dushyantss** [comment]
Hey @msaraiva and @Malian thanks for taking the time to look into it.

The issue is exactly as @Malian has put it. I want surface catalogue to be available only in development environment, but I also want to deploy the application to prod. Currently the generation of a production release fails due to the error mentioned. The steps provided by @Malian should allow reproduction of the issue.

**Comment by msaraiva** [comment]
Ohh, Sorry. I misunderstood :)

This commit should fix it https://github.com/surface-ui/surface_catalogue/commit/d3746ea05f8ae4b0c732fc1952f28c8992001315. Can you give it a try?

**Comment by Malian** [comment]
It works for me. @dushyantss does it fix your issue?

**Comment by dushyantss** [comment]
Hey,

Thanks for the fix. With this I have been able to move `phoenix_live_reload` back to dev environment. But, I still have to keep `surface_catalogue` as a prod dependency because we add `import Surface.Catalogue.Router` to `router.ex`. Thus, my mix.exs contains this `{:surface_catalogue, github: "surface-ui/surface_catalogue", ref: "d3746ea"},`

If we don't add `surface_catalogue` to prod dependencies, we get the following error when building a prod build.
```shell
== Compilation error in file lib/recast_web/router.ex ==
** (CompileError) lib/<project-name>/router.ex:6: module Surface.Catalogue.Router is not loaded and could not be found

```

**Comment by msaraiva** [comment]
Hi @dushyantss!

Just move the import to inside the `if` block. Like:

```elixir
  if Mix.env() == :dev do
    import Surface.Catalogue.Router

    scope "/" do
      pipe_through :browser

      surface_catalogue "/"
    end
  end
```

It should work just fine.

**Comment by dushyantss** [comment]
I am so sorry but I am most certainly missing something here.

First let me post relevant portions of the code. If something else may affect it too, please tell me and I'll post that too.
`mix.exs`
```elixir
      {:surface_catalogue,
       github: "surface-ui/surface_catalogue", ref: "d3746ea", only: [:dev, :test]},
```

`router.ex`
```elixir
  if Mix.env() == :dev do
    import Surface.Catalogue.Router

    scope "/" do
      pipe_through(:browser)
      surface_catalogue("/catalogue")
    end
  end
```

Now, I run this command
```shell
SECRET_KEY_BASE=$(mix phx.gen.secret) DATABASE_URL=<database-url> MIX_ENV=prod mix release
```

Then I get this error
```shell
== Compilation error in file lib/<project_name>/router.ex ==
** (CompileError) lib/<project_name>/router.ex:131: module Surface.Catalogue.Router is not loaded and could not be found
    (stdlib 3.14.1) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14.1) lists.erl:1359: :lists.mapfoldl/3
    (elixir 1.11.4) expanding macro: Kernel.if/2
```

I faced the same issue when using the steps provided in https://github.com/surface-ui/surface_catalogue/issues/7#issuecomment-814607549 😅

**Comment by msaraiva** [comment]
@dushyantss I'm afraid you won't be able to set the `surface_catalogue` dependency just for `:dev`. The problem, I believe, is that since `surface_catalogue/2` is a macro, it has to be evaluated at compile-time, no matter if there's a sorrowing `if` or not. This is the same approach as the [Live Dashboard](https://github.com/phoenixframework/phoenix_live_dashboard#1-add-the-phoenix_live_dashboard-dependency).

However, I wouldn't worry much about having this dependency in prod since there will be no route available for it and no example nor playground loaded (assuming you set up the catalogue properly).

The `phoenix_live_reload` issue was something we had to solve anyway. Regarding this one, I'm afraid there's not much we can do about it but as I said, I don't think you should worry about it.

**Comment by dushyantss** [comment]
Exactly what I understood and completely understandable. I'll get to remove live_reload from prod dependencies and that in itself is a win for me 😄 . We may want to update the installation instructions in the README.

Again thanks a lot to you both @msaraiva and @Malian 😄
