### ISSUE TITLE
Using the catalogue to display custom liveview components

### ISSUE THREAD

**Issue by ivanminutillo** [surface-ui/surface_catalogue#9]
Hello,
I was looking for alternatives to storybook for liveview components and stumbled upon you great work!
I was wondering if it could be possible to use the catalogue as a playground for custom liveview stateless components, or is it currently only bound to surface modules?
Thanks in advance

**Comment by msaraiva** [comment]
Hi @ivanminutillo!

Currently, it can only work with Surface components as vanilla LV components don't have an API to define nor introspect properties yet.
